from fantrax_pl_team_manager.domain.constants import *

# Position mapping constants
POSITION_MAP_BY_ID = {
    "704": POSITION_KEY_GOALKEEPER,
    "703": POSITION_KEY_DEFENDER,
    "702": POSITION_KEY_MIDFIELDER,
    "701": POSITION_KEY_FORWARD,
}

POSITION_MAP_BY_SHORT_NAME = {v: k for k, v in POSITION_MAP_BY_ID.items()}

# Status icon mapping constants
STATUS_ICON_MAP_BY_ID = {
    "12": "starting",
    "34": "benched",
    "15": "out",
    "32": "expected-to-play",
    "30": "out-for-next-game",
    "1": "uncertain-gametime-decision",
    "6": "suspended"
}

# Roster status constants
ROSTER_STATUS_STARTER = "1"
ROSTER_STATUS_RESERVE = "2"

# Fantrax Premier League table header name constants
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_GAMES_PLAYED = "Games Played"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_WINS = "Wins"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_LOSSES = "Losses"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_TIES_OR_OVERTIME_LOSS = "Ties Or Overtime Losses"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_POINTS = "Points"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_GOALS_FOR = "Goals For"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_GOALS_AGAINST = "Goals Against"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_GOAL_DIFFERENCE = "Goal Difference"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_HOME_RECORD = "Home Record"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_AWAY_RECORD = "Away Record"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_LAST_TEN_RECORD = "Last Ten Record"
FANTRAX_PREMIERE_LEAGUE_TABLE_HEADER_NAME_CURRENT_STREAK = "Current Streak"

# Fantrax Player Recent Games table header name constants
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_DATE = "Date"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_TEAM = "Team"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_OPPONENT = "Opponent"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_SCORE = "Score"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_GAMES_STARTED = "Games Started"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_MINUTES_PLAYED = "Minutes Played"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_GOALS = "Goals"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_ASSISTS = "Assists (Official)"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_POINTS = "Fantasy Points"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_SHOTS = "Shots"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_SHOTS_ON_TARGET = "Shots on Target"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_FOULS_COMMITTED = "Fouls Committed"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_FOULS_SUFFERED = "Fouls Suffered"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_YELLOW_CARDS = "Yellow Cards"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_RED_CARDS = "Red Cards"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_OFFSIDES = "Offsides"
FANTRAX_PLAYER_RECENT_GAMES_TABLE_HEADER_NAME_PENALTY_KICK_GOALS = "Penalty Kick Goals"
