# TODO: Use these as keys for team name mapping in:
#   [ ] integrations/the_odds_api/mappers/
#   [ ] integrations/fantrax/mappers/
EPL_TEAM_NAME_ARSENAL = "Arsenal"
EPL_TEAM_NAME_ASTON_VILLA = "Aston Villa"
EPL_TEAM_NAME_BOURNEMOUTH = "Bournemouth"
EPL_TEAM_NAME_BRENTFORD = "Brentford"
EPL_TEAM_NAME_BRIGHTON_AND_HOVE_ALBION = "Brighton and Hove Albion"
EPL_TEAM_NAME_BURNLEY = "Burnley"
EPL_TEAM_NAME_CHELSEA = "Chelsea"
EPL_TEAM_NAME_CRYSTAL_PALACE = "Crystal Palace"
EPL_TEAM_NAME_EVERTON = "Everton"
EPL_TEAM_NAME_FULHAM = "Fulham"
EPL_TEAM_NAME_LEEDS_UNITED = "Leeds United"
EPL_TEAM_NAME_LIVERPOOL = "Liverpool"
EPL_TEAM_NAME_MANCHESTER_CITY = "Manchester City"
EPL_TEAM_NAME_MANCHESTER_UNITED = "Manchester United"
EPL_TEAM_NAME_NEWCASTLE_UNITED = "Newcastle"
EPL_TEAM_NAME_NOTTINGHAM_FOREST = "Nottingham"
EPL_TEAM_NAME_SUNDERLAND = "Sunderland"
EPL_TEAM_NAME_TOTTENHAM_HOTSPUR = "Tottenham"
EPL_TEAM_NAME_WEST_HAM_UNITED = "West Ham"
EPL_TEAM_NAME_WOLVERHAMPTON_WANDERERS = "Wolverhampton"


POSITION_KEY_GOALKEEPER = "G"
POSITION_KEY_DEFENDER = "D"
POSITION_KEY_MIDFIELDER = "M"
POSITION_KEY_FORWARD = "F"

# Lineup requirement constants
MIN_STARTERS = 11
MIN_DEFENDERS = 3
MIN_MIDFIELDERS = 3
MIN_FORWARDS = 1
MAX_GOALKEEPERS = 1
MAX_DEFENDERS = 5
MAX_MIDFIELDERS = 5
MAX_FORWARDS = 3
MAX_RECENT_GAMEWEEKS = 5

# Status string constants
STATUS_BENCHED = "benched"
STATUS_SUSPENDED = "suspended"
STATUS_OUT = "out"
STATUS_OUT_FOR_NEXT_GAME = "out-for-next-game"
STATUS_STARTING = "starting"
STATUS_EXPECTED_TO_PLAY = "expected-to-play"
STATUS_UNCERTAIN_GAMETIME_DECISION = "uncertain-gametime-decision"
