POSITION_KEY_GOALKEEPER = "G"
POSITION_KEY_DEFENDER = "D"
POSITION_KEY_MIDFIELDER = "M"
POSITION_KEY_FORWARD = "F"

# Lineup requirement constants
MIN_STARTERS = 11
MIN_DEFENDERS = 3
MIN_MIDFIELDERS = 3
MIN_FORWARDS = 1
MAX_GOALKEEPERS = 1
MAX_DEFENDERS = 5
MAX_MIDFIELDERS = 5
MAX_FORWARDS = 3
MAX_RECENT_GAMEWEEKS = 5

# Status string constants
STATUS_BENCHED = "benched"
STATUS_SUSPENDED = "suspended"
STATUS_OUT = "out"
STATUS_OUT_FOR_NEXT_GAME = "out-for-next-game"
STATUS_STARTING = "starting"
STATUS_EXPECTED_TO_PLAY = "expected-to-play"
STATUS_UNCERTAIN_GAMETIME_DECISION = "uncertain-gametime-decision"

# Fantasy value calculation constants
DEFAULT_UPCOMING_GAME_COEFFICIENT_K = 0.7
DEFAULT_UPCOMING_GAME_COEFFICIENT_A = 1
